steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/orcast-backend-fixed',
      '-f', 'Dockerfile.fixed',
      '.'
    ]
images:
  - 'gcr.io/$PROJECT_ID/orcast-backend-fixed' 