// Typed loader for the real h5-derived DTAG fixture. The JSON is generated by
// infra/tagtools/bake.py from the real humpback DTAG mn09_203a data (contrast/
// reference only). Do NOT hand-edit the JSON; re-run the bake.

import type { DtagFixture } from "../types";
import raw from "./dtag_mn09_203a.json";

export const dtagFixture: DtagFixture = raw as unknown as DtagFixture;

export function loadDtagFixture(): DtagFixture {
  return dtagFixture;
}
