#!/usr/bin/env python3
"""
Build self-contained arXiv tarballs for orcast whitepapers.

Usage:
  python3 tools/testing/build_arxiv_bundle.py --paper whitepaper1
  python3 tools/testing/build_arxiv_bundle.py --paper whitepaper2
  python3 tools/testing/build_arxiv_bundle.py --paper both

Each bundle is written to:
  docs/whitepaper/Build/arxiv/orcast_whitepaper1_arxiv.tar.gz
  docs/whitepaper2/Build/arxiv/orcast_grounding_arxiv.tar.gz

Validation: extract to a temp dir, run pdflatex + biber + pdflatex, confirm success.
"""
from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
import tarfile
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]


# ── Paper configs ─────────────────────────────────────────────────────────────

PAPERS = {
    "whitepaper1": {
        "lx_dir": REPO / "docs/whitepaper/LX",
        "root_tex": "Raitses_orcast_2026_share.tex",
        "bib_file": "references.bib",
        "sections_dir": "Sections",
        "figures_dir": "Figures",
        "extra_files": [],
        "out_dir": REPO / "docs/whitepaper/Build/arxiv",
        "bundle_name": "orcast_whitepaper1_arxiv.tar.gz",
        "display_name": "orcast whitepaper 1",
    },
    "whitepaper2": {
        "lx_dir": REPO / "docs/whitepaper2/LX",
        "root_tex": "Raitses_orcast_grounding_2026_share.tex",
        "bib_file": "references2.bib",
        "sections_dir": "Sections",
        "figures_dir": "Figures",
        "extra_files": [],
        "out_dir": REPO / "docs/whitepaper2/Build/arxiv",
        "bundle_name": "orcast_grounding_arxiv.tar.gz",
        "display_name": "orcast whitepaper 2 (grounding)",
    },
}


def readme_content(cfg: dict) -> str:
    root = Path(cfg["root_tex"]).stem
    bib = cfg["bib_file"]
    return f"""\
# {cfg['display_name']} — arXiv bundle

## Build instructions

  pdflatex {cfg['root_tex']}
  biber {root}
  pdflatex {cfg['root_tex']}

Requires: pdflatex (TeX Live 2022+), biber.

## Contents

- {cfg['root_tex']}  — root document
- {bib}              — bibliography
- {cfg['sections_dir']}/  — section .tex files
- {cfg['figures_dir']}/   — figure files (PNG)

Generated by tools/testing/build_arxiv_bundle.py
"""


def build_bundle(key: str, validate: bool = True) -> Path:
    cfg = PAPERS[key]
    lx = Path(cfg["lx_dir"])
    out_dir = Path(cfg["out_dir"])
    out_dir.mkdir(parents=True, exist_ok=True)
    bundle_path = out_dir / cfg["bundle_name"]

    with tempfile.TemporaryDirectory(prefix="arxiv_stage_") as stage:
        stage_dir = Path(stage)

        # Root .tex
        shutil.copy2(lx / cfg["root_tex"], stage_dir / cfg["root_tex"])

        # .bib
        bib_src = lx / cfg["bib_file"]
        if bib_src.exists():
            shutil.copy2(bib_src, stage_dir / cfg["bib_file"])
        else:
            print(f"  WARNING: {bib_src} not found — bundle may fail to build")

        # Sections
        sections_src = lx / cfg["sections_dir"]
        if sections_src.exists():
            shutil.copytree(sections_src, stage_dir / cfg["sections_dir"])

        # Figures (PNG and PDF files only; skip large source files)
        figures_src = lx / cfg["figures_dir"]
        figures_dst = stage_dir / cfg["figures_dir"]
        figures_dst.mkdir(exist_ok=True)
        if figures_src.exists():
            for f in figures_src.iterdir():
                if f.suffix.lower() in {".png", ".pdf", ".jpg", ".jpeg", ".eps"}:
                    shutil.copy2(f, figures_dst / f.name)

        # Extra files
        for extra in cfg["extra_files"]:
            src = lx / extra
            if src.exists():
                shutil.copy2(src, stage_dir / Path(extra).name)

        # README
        (stage_dir / "README.md").write_text(readme_content(cfg))

        # Create tarball
        with tarfile.open(bundle_path, "w:gz") as tar:
            tar.add(stage_dir, arcname=".")

        print(f"  Bundle: {bundle_path} ({bundle_path.stat().st_size // 1024} KB)")

        if validate:
            _validate(cfg, stage_dir)

    return bundle_path


def _validate(cfg: dict, stage_dir: Path) -> None:
    """Extract bundle to a temp dir and try to build the PDF."""
    bundle_path = Path(cfg["out_dir"]) / cfg["bundle_name"]

    with tempfile.TemporaryDirectory(prefix="arxiv_validate_") as val:
        val_dir = Path(val)
        with tarfile.open(bundle_path, "r:gz") as tar:
            tar.extractall(val_dir)

        root = cfg["root_tex"]
        stem = Path(root).stem
        env = {**os.environ, "TEXINPUTS": f"{val_dir}:"}

        def run(*cmd: str) -> int:
            res = subprocess.run(list(cmd), cwd=val_dir, capture_output=True)
            return res.returncode

        rc1 = run("pdflatex", "-interaction=batchmode", root)
        rc2 = run("biber", stem)
        rc3 = run("pdflatex", "-interaction=batchmode", root)

        pdf = val_dir / f"{stem}.pdf"
        if pdf.exists() and rc3 == 0:
            print(f"  Validation: PASS ({pdf.stat().st_size // 1024} KB)")
        else:
            # Some references may not resolve in isolation; partial build still passes
            # as long as PDF was generated on the final pass.
            if pdf.exists():
                print(f"  Validation: PARTIAL — PDF built ({pdf.stat().st_size // 1024} KB)"
                      f" but biber/pdflatex returned non-zero (rc1={rc1} rc2={rc2} rc3={rc3})")
            else:
                print(f"  Validation: FAIL — no PDF generated (rc1={rc1} rc2={rc2} rc3={rc3})",
                      file=sys.stderr)


def main() -> None:
    parser = argparse.ArgumentParser(description="Build arXiv tarballs for orcast whitepapers")
    parser.add_argument(
        "--paper",
        choices=["whitepaper1", "whitepaper2", "both"],
        default="both",
        help="Which paper to bundle",
    )
    parser.add_argument("--no-validate", action="store_true", help="Skip build validation")
    args = parser.parse_args()

    targets = list(PAPERS.keys()) if args.paper == "both" else [args.paper]
    for key in targets:
        print(f"\nBundling {PAPERS[key]['display_name']}…")
        build_bundle(key, validate=not args.no_validate)

    print("\nDone.")


if __name__ == "__main__":
    main()
